site_name: "pruebaunotemplate"
site_description: "prueba numero 1 del template "

nav:
  - Introduction: index.md
  - API Reference:
    - Overview: api.md
    - Endpoints: endpoints.md

plugins:
  - techdocs-core